"""initial schema

Revision ID: 3de2908b9836
Revises:
Create Date: 2026-08-11 02:13:38.963798

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom TypeDecorators (e.g. UtcDateTime) are rendered fully qualified by
# autogenerate, so the module must be importable in every migration.
import komora.db.base

# revision identifiers, used by Alembic.
revision: str = "3de2908b9836"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_client_registration",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("created_at", komora.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("silpo_tokens", sa.LargeBinary(), nullable=True),
        sa.Column(
            "silpo_token_expires_at", komora.db.base.UtcDateTime(timezone=True), nullable=True
        ),
        sa.Column("branch_id", sa.String(length=64), nullable=True),
        sa.Column("budget_weekly", sa.Integer(), nullable=True),
        sa.Column("created_at", komora.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("telegram_id"),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", komora.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversations_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_conversations_user_id_id", ["user_id", "id"], unique=False)

    op.create_table(
        "draft_baskets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("intent", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("estimated_savings", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("savings_notes", sa.Text(), nullable=False),
        sa.Column("warnings", sa.Text(), nullable=False),
        sa.Column("created_at", komora.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("draft_baskets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_draft_baskets_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_draft_baskets_user_id"), ["user_id"], unique=False)

    op.create_table(
        "draft_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("basket_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("company_id", sa.String(length=64), nullable=False),
        sa.Column("branch_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("qty", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("reason_kind", sa.String(length=16), nullable=False),
        sa.Column("reason_text", sa.Text(), nullable=False),
        sa.Column("substituted_from", sa.Text(), nullable=True),
        sa.Column("optional", sa.Boolean(), nullable=False),
        sa.Column("unavailable", sa.Boolean(), nullable=False),
        sa.Column("removed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["basket_id"], ["draft_baskets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("draft_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_draft_items_basket_id"), ["basket_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("draft_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_draft_items_basket_id"))

    op.drop_table("draft_items")
    with op.batch_alter_table("draft_baskets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_draft_baskets_user_id"))
        batch_op.drop_index(batch_op.f("ix_draft_baskets_status"))

    op.drop_table("draft_baskets")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index("ix_conversations_user_id_id")
        batch_op.drop_index(batch_op.f("ix_conversations_user_id"))

    op.drop_table("conversations")
    op.drop_table("users")
    op.drop_table("oauth_client_registration")
    # ### end Alembic commands ###
