"""draft item description and old price

Revision ID: 4cd5a1cfbd44
Revises: 3de2908b9836
Create Date: 2026-08-12 03:01:36.768024

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# Custom TypeDecorators (e.g. UtcDateTime) are rendered fully qualified by
# autogenerate, so the module must be importable in every migration.


# revision identifiers, used by Alembic.
revision: str = "4cd5a1cfbd44"
down_revision: str | Sequence[str] | None = "3de2908b9836"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    `description` carries a `server_default`, which autogenerate did not add: the model
    declares a Python-side default, and that produces no DDL. SQLite then refuses to
    add a NOT NULL column to a table that already has rows, so the migration failed on
    the first database that was not empty — which is every real one.
    """
    with op.batch_alter_table("draft_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=False, server_default=""))
        batch_op.add_column(
            sa.Column("old_price", sa.Numeric(precision=10, scale=2), nullable=True)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("draft_items", schema=None) as batch_op:
        batch_op.drop_column("old_price")
        batch_op.drop_column("description")

    # ### end Alembic commands ###
