"""coupon notes and line category

Revision ID: 7aa53814a7dd
Revises: 4cd5a1cfbd44
Create Date: 2026-08-12 12:50:56.824362

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom TypeDecorators (e.g. UtcDateTime) are rendered fully qualified by
# autogenerate, so the module must be importable in every migration.


# revision identifiers, used by Alembic.
revision: str = "7aa53814a7dd"
down_revision: str | Sequence[str] | None = "4cd5a1cfbd44"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    `coupon_notes` needs a `server_default`; autogenerate never adds one, because the
    model declares a Python-side default that produces no DDL. SQLite refuses to add a
    NOT NULL column to a table with rows without it — the same trap as
    `draft_items.description` one migration ago, and it fails only on a database that
    already holds data.
    """
    with op.batch_alter_table("draft_baskets", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("coupon_notes", sa.Text(), nullable=False, server_default="[]")
        )

    with op.batch_alter_table("draft_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("category", sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("draft_items", schema=None) as batch_op:
        batch_op.drop_column("category")

    with op.batch_alter_table("draft_baskets", schema=None) as batch_op:
        batch_op.drop_column("coupon_notes")

    # ### end Alembic commands ###
