"""habits: purchases, product habits, mutes, imports, notifications

Revision ID: e3460e4eec92
Revises: 9b41c07ae512
Create Date: 2026-09-14 04:18:06.390440

Plan 3. Five new tables and two nullable columns on `users`; nothing here adds a NOT
NULL column to an existing table, so no `server_default` is needed (see
`tests/test_migrations.py` for why that matters). `product_habits` is a recompute of
`purchases` and can be emptied at any time; `habit_mutes` is the user's own state and
cannot.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom TypeDecorators (e.g. UtcDateTime) are rendered fully qualified by
# autogenerate, so the module must be importable in every migration.
import komora.db.base

# revision identifiers, used by Alembic.
revision: str = "e3460e4eec92"
down_revision: str | Sequence[str] | None = "9b41c07ae512"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "habit_mutes",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("product_key", sa.String(length=64), nullable=False),
        sa.Column("muted_at", komora.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "product_key"),
    )
    op.create_table(
        "history_imports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("at", komora.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("outcome", sa.String(length=8), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("history_imports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_history_imports_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_history_imports_user_source_at", ["user_id", "source", "at"], unique=False
        )

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("subject_key", sa.String(length=64), nullable=False),
        sa.Column("sent_at", komora.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_notifications_user_kind_subject", ["user_id", "kind", "subject_key"], unique=False
        )

    op.create_table(
        "product_habits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("product_key", sa.String(length=64), nullable=False),
        sa.Column("group_key", sa.String(length=64), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("external_product_id", sa.BigInteger(), nullable=True),
        sa.Column("unit", sa.String(length=64), nullable=False),
        sa.Column("weighted", sa.Boolean(), nullable=False),
        sa.Column("reorderable", sa.Boolean(), nullable=False),
        sa.Column("events", sa.Integer(), nullable=False),
        sa.Column("median_gap_days", sa.Float(), nullable=False),
        sa.Column("cv", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("last_bought_on", sa.Date(), nullable=False),
        sa.Column("last_qty", sa.Float(), nullable=False),
        sa.Column("median_qty", sa.Float(), nullable=False),
        sa.Column("due_on", sa.Date(), nullable=False),
        sa.Column("computed_at", komora.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "product_key", name="uq_product_habit"),
    )
    with op.batch_alter_table("product_habits", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_product_habits_user_id"), ["user_id"], unique=False)

    op.create_table(
        "purchases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("receipt_key", sa.String(length=80), nullable=False),
        sa.Column("product_key", sa.String(length=64), nullable=False),
        sa.Column("external_product_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("qty", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("weighted", sa.Boolean(), nullable=False),
        sa.Column("reorderable", sa.Boolean(), nullable=False),
        sa.Column("bought_at", komora.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "source", "receipt_key", "product_key", name="uq_purchase"),
    )
    with op.batch_alter_table("purchases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_purchases_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_purchases_user_id_bought_at", ["user_id", "bought_at"], unique=False
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("quiet_from", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("quiet_to", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("quiet_to")
        batch_op.drop_column("quiet_from")

    with op.batch_alter_table("purchases", schema=None) as batch_op:
        batch_op.drop_index("ix_purchases_user_id_bought_at")
        batch_op.drop_index(batch_op.f("ix_purchases_user_id"))

    op.drop_table("purchases")
    with op.batch_alter_table("product_habits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_habits_user_id"))

    op.drop_table("product_habits")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index("ix_notifications_user_kind_subject")
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))

    op.drop_table("notifications")
    with op.batch_alter_table("history_imports", schema=None) as batch_op:
        batch_op.drop_index("ix_history_imports_user_source_at")
        batch_op.drop_index(batch_op.f("ix_history_imports_user_id"))

    op.drop_table("history_imports")
    op.drop_table("habit_mutes")
    # ### end Alembic commands ###
